import * as Icon from 'react-feather';

const SidebarData = [
  { caption: 'Personal' },
  {
    title: 'Dashboards',
    href: '/dashboards',
    id: 1,
    suffix: '4',
    suffixColor: 'bg-cyan rounded-pill text-dark-white',
    icon: <Icon.Home />,
    collapisble: true,
    children: [
      {
        title: 'Minimal',
        href: '/dashboards/minimal',
        icon: <Icon.Disc />,
        id: 1.1,
        collapisble: false,
      },
      {
        title: 'Analytical',
        href: '/dashboards/analytical',
        icon: <Icon.Disc />,
        id: 1.2,
        collapisble: false,
      },
      {
        title: 'Demographical',
        href: '/dashboards/demographical',
        icon: <Icon.Disc />,
        id: 1.3,
        collapisble: false,
      },
      {
        title: 'Modern',
        href: '/dashboards/modern',
        icon: <Icon.Disc />,
        id: 1.4,
        collapisble: false,
      },
    ],
  },
  { caption: 'Apps' },
 
  // {
  //   title: 'User List',
  //   href: '/user-list',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Category',
  //   href: '/category',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Posters',
  //   href: '/poster',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  {
    title: 'Books Management',
    href: '/books-management',
    icon: <Icon.ShoppingCart />,
    id: 2.7,
    collapisble: true,
    children: [
      {
        title: 'Books List',
        href: '/books-management/books',
        icon: <Icon.Disc />,
      },
      {
        title: 'Add Book',
        href: '/books-management/add-books',
        icon: <Icon.Disc />,
      },
      {
        title: 'Book Files',
        href: '/books-management/book-files',
        icon: <Icon.Disc />,
      },
    ],
  },
  {
    title: 'Profile',
    href: '/profile-info',
    icon: <Icon.FileText />,
    id: 2.1,
    collapisble: false,
  },
  {
    title: 'Change Password',
    href: '/change-password',
    icon: <Icon.FileText />,
    id: 2.3,
    collapisble: false,
  },
  // {
  //   title: 'Books Files',
  //   href: '/bookfiles',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Current Affairs',
  //   href: '/current-affairs',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Test Series',
  //   href: '/test-series',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Design',
  //   href: '/design',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Previous Year',
  //   href: '/previous-year',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Typing data',
  //   href: '/typing-data',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Data translate',
  //   href: '/data-translate',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Trending Titles',
  //   href: '/trending-titles',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Admin Information',
  //   href: '/admin-information',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Flash Message',
  //   href: '/flash-message',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Permotion Popup',
  //   href: '/permotion-popup',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Social Media Information',
  //   href: '/social-media',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Promotion and offers',
  //   href: '/promotion-and-offers',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Reviews',
  //   href: '/reviews',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Cart Details',
  //   href: '/cart',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Support',
  //   href: '/support',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Coaching Management',
  //   href: '/coaching-management',
  //   icon: <Icon.ShoppingCart />,
  //   id: 2.7,
  //   collapisble: true,
  //   children: [
  //     {
  //       title: 'Coaching List',
  //       href: '/coaching-management/coaching-list',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Coaching Add',
  //       href: '/coaching-management/coaching-add',
  //       icon: <Icon.Disc />,
  //     },
  //   ],
  // },
  // {
  //   title: 'Satff Management',
  //   href: '/staff-management',
  //   icon: <Icon.ShoppingCart />,
  //   id: 2.7,
  //   collapisble: true,
  //   children: [
  //     {
  //       title: 'Staff List',
  //       href: '/staff-management/staff-list',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Staff Add',
  //       href: '/staff-management/staff-add',
  //       icon: <Icon.Disc />,
  //     },
  //   ],
  // },
  // {
  //   title: 'Chat',
  //   href: '/apps/chat',
  //   icon: <Icon.MessageCircle />,
  //   id: 2.2,
  //   collapisble: false,
  // },
  // {
  //   title: 'Notes',
  //   href: '/apps/notes',
  //   icon: <Icon.FileText />,
  //   id: 2.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'Contacts',
  //   href: '/apps/contacts',
  //   icon: <Icon.User />,
  //   id: 2.3,
  //   collapisble: false,
  // },
  // {
  //   title: 'Calendar',
  //   href: '/apps/calendar',
  //   icon: <Icon.Calendar />,
  //   id: 2.4,
  //   collapisble: false,
  // },
  // {
  //   title: 'Email',
  //   href: '/apps/email',
  //   icon: <Icon.Mail />,
  //   suffix: 'New',
  //   suffixColor: 'bg-primary rounded-pill text-dark-white',
  //   id: 2.5,
  //   collapisble: false,
  // },
  // {
  //   title: 'CASL',
  //   href: '/casl',
  //   icon: <Icon.UserCheck />,
  //   id: 2.6,
  //   collapisble: false,
  // },
  // {
  //   title: 'Ecommerce',
  //   href: '/ecom',
  //   icon: <Icon.ShoppingCart />,
  //   id: 2.7,
  //   collapisble: true,
  //   children: [
  //     {
  //       title: 'Shop',
  //       href: '/ecom/shop',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Shop Detail',
  //       href: '/ecom/shopdetail',
  //       icon: <Icon.Disc />,
  //     },
  //   ],
  // },
  // {
  //   title: 'Ticket',
  //   href: '/tickt',
  //   icon: <Icon.Bookmark />,
  //   id: 2.8,
  //   collapisble: true,
  //   children: [
  //     {
  //       title: 'Ticket List',
  //       href: '/tickt/ticket-list',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Ticket Detail',
  //       href: '/tickt/ticket-detail',
  //       icon: <Icon.Disc />,
  //     },
  //   ],
  // },
  // {
  //   title: 'TreeView',
  //   href: '/apps/treeview',
  //   icon: <Icon.Triangle />,
  //   id: 2.9,
  //   collapisble: false,
  // },
  // { caption: 'UI' },
  // {
  //   title: 'UI Elements',
  //   href: '/ui',
  //   id: 2,
  //   suffix: '22',
  //   suffixColor: 'bg-info rounded-pill text-dark-white',
  //   icon: <Icon.Cpu />,
  //   collapisble: true,
  //   children: [
  //     {
  //       title: 'Alert',
  //       href: '/ui/alerts',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Badges',
  //       href: '/ui/badges',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Buttons',
  //       href: '/ui/buttons',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Button Group',
  //       href: '/ui/button-group',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Breadcrumbs',
  //       href: '/ui/breadcrumbs',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Cards',
  //       href: '/ui/cards',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Collapse',
  //       href: '/ui/collapse',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Dropdown',
  //       href: '/ui/dropdown',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Grid',
  //       href: '/ui/grid',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'List Group',
  //       href: '/ui/list-group',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Modal',
  //       href: '/ui/modal',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Navbar',
  //       href: '/ui/navbar',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Navs',
  //       href: '/ui/nav',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Pagination',
  //       href: '/ui/pagination',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Popover',
  //       href: '/ui/popover',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Progress',
  //       href: '/ui/progress',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Spinner',
  //       href: '/ui/spinner',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Tabs',
  //       href: '/ui/tabs',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Toasts',
  //       href: '/ui/toasts',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Tooltip',
  //       href: '/ui/tooltip',
  //       icon: <Icon.Disc />,
  //     },
  //   ],
  // },
  // { caption: 'Forms' },
  // {
  //   title: 'Form Layouts',
  //   href: '/form-layout',
  //   icon: <Icon.FileText />,
  //   id: 3.1,
  //   collapisble: true,
  //   children: [
  //     {
  //       title: 'Basic Forms',
  //       href: '/form-layout/form-basic',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Form Grid',
  //       href: '/form-layout/form-grid',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Form Group',
  //       href: '/form-layout/form-group',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Form Input',
  //       href: '/form-layout/form-input',
  //       icon: <Icon.Disc />,
  //     },
  //   ],
  // },
  // {
  //   title: 'Form Pickers',
  //   href: '/form-pickers',
  //   icon: <Icon.Droplet />,
  //   id: 3.2,
  //   collapisble: true,
  //   children: [
  //     {
  //       title: 'Datepicker',
  //       href: '/form-pickers/datepicker',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Tags & Select',
  //       href: '/form-pickers/tag-select',
  //       icon: <Icon.Disc />,
  //     },
  //   ],
  // },
  // {
  //   title: 'Form Validation',
  //   href: '/form-validation',
  //   icon: <Icon.CheckSquare />,
  //   id: 3.3,
  //   collapisble: false,
  // },
  // {
  //   title: 'Form Steps',
  //   href: '/form-steps',
  //   icon: <Icon.CreditCard />,
  //   id: 3.4,
  //   collapisble: false,
  // },
  // {
  //   title: 'Form Editor',
  //   href: '/form-editor',
  //   icon: <Icon.Edit />,
  //   id: 3.5,
  //   collapisble: false,
  // },
  // { caption: 'Tables' },
  // {
  //   title: 'Basic Table',
  //   href: '/tables/basic-table',
  //   icon: <Icon.Codepen />,
  //   id: 4.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'React Table',
  //   href: '/tables/react-table',
  //   icon: <Icon.Disc />,
  //   id: 4.2,
  //   collapisble: false,
  // },
  // {
  //   title: 'Bootstrap Datatable',
  //   href: '/tables/data-table',
  //   icon: <Icon.HardDrive />,
  //   id: 4.3,
  //   collapisble: false,
  // },
  // { caption: 'Charts' },
  // {
  //   title: 'Apexchart',
  //   href: '/charts/apex',
  //   icon: <Icon.Loader />,
  //   id: 5.1,
  //   collapisble: false,
  // },
  // {
  //   title: 'ChartJs',
  //   href: '/charts/chartjs',
  //   icon: <Icon.PieChart />,
  //   id: 5.2,
  //   collapisble: false,
  // },
  // { caption: 'Extra' },
  // {
  //   title: 'Sample Pages',
  //   href: '/sample-pages',
  //   icon: <Icon.BookOpen />,
  //   id: 6.1,
  //   collapisble: true,
  //   children: [
  //     {
  //       title: 'Starterkit',
  //       href: '/sample-pages/starterkit',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Profile',
  //       href: '/sample-pages/profile',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Search Result',
  //       href: '/sample-pages/search-result',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Gallery',
  //       href: '/sample-pages/gallery',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Helper Class',
  //       href: '/sample-pages/helper-class',
  //       icon: <Icon.Disc />,
  //     },
  //   ],
  // },
  // {
  //   title: 'Widget',
  //   href: '/widget',
  //   icon: <Icon.Grid />,
  //   id: 6.4,
  //   collapisble: false,
  // },
  // {
  //   title: 'Icons',
  //   href: '/icons',
  //   icon: <Icon.Feather />,
  //   id: 6.2,
  //   collapisble: true,
  //   children: [
  //     {
  //       title: 'Bootstrap',
  //       href: '/icons/bootstrap',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Feather',
  //       href: '/icons/feather',
  //       icon: <Icon.Disc />,
  //     },
  //   ],
  // },
  // {
  //   title: 'Vector Map',
  //   href: '/map/vector',
  //   icon: <Icon.Map />,
  //   id: 6.3,
  //   collapisble: false,
  // },
  // {
  //   title: 'Authentication',
  //   href: '/auth',
  //   icon: <Icon.Lock />,
  //   id: 6.5,
  //   collapisble: true,
  //   children: [
  //     {
  //       title: 'Login',
  //       href: '/auth/loginformik',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Register',
  //       href: '/auth/registerformik',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Maintanance',
  //       href: '/auth/maintanance',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Lockscreen',
  //       href: '/auth/lockscreen',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Recover Password',
  //       href: '/auth/recoverpwd',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Error',
  //       href: '/auth/404',
  //       icon: <Icon.Disc />,
  //     },
  //   ],
  // },
  // {
  //   title: 'DD Menu',
  //   href: '/',
  //   id: 7,
  //   collapisble: true,
  //   icon: <Icon.Disc />,
  //   children: [
  //     {
  //       title: 'Simple dd 1',
  //       href: '/',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Simple dd 2',
  //       href: '/',
  //       icon: <Icon.Disc />,
  //     },
  //     {
  //       title: 'Simple dd 3',
  //       href: '/',
  //       icon: <Icon.Disc />,
  //       children: [
  //         {
  //           title: 'Simple dd 1.1',
  //           href: '/alerts',
  //           icon: <Icon.Disc />,
  //         },
  //       ],
  //     },
  //   ],
  // },
];

export default SidebarData;
